version: 2.1

orbs:
  yarn: itinerisltd/yarn@2.1.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test