version: 2.1

orbs:
  node: circleci/node@4.6.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test